# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDockWidget, QFrame,
    QGridLayout, QHBoxLayout, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSpacerItem,
    QSplitter, QStatusBar, QToolBar, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1276, 882)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setAnimated(True)
        self.setting_atn = QAction(MainWindow)
        self.setting_atn.setObjectName(u"setting_atn")
        self.setting_atn.setCheckable(True)
        self.setting_atn.setChecked(True)
        icon = QIcon()
        icon.addFile(u":/iocns/icons/setting_dark.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.setting_atn.setIcon(icon)
        self.load_atn = QAction(MainWindow)
        self.load_atn.setObjectName(u"load_atn")
        icon1 = QIcon()
        icon1.addFile(u":/iocns/icons/openfile_dark.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.load_atn.setIcon(icon1)
        self.load_atn.setMenuRole(QAction.MenuRole.NoRole)
        self.load_atn.setIconVisibleInMenu(True)
        self.save_atn = QAction(MainWindow)
        self.save_atn.setObjectName(u"save_atn")
        icon2 = QIcon()
        icon2.addFile(u":/iocns/icons/save_dark.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.save_atn.setIcon(icon2)
        self.exit_action = QAction(MainWindow)
        self.exit_action.setObjectName(u"exit_action")
        self.save_action = QAction(MainWindow)
        self.save_action.setObjectName(u"save_action")
        self.open_action = QAction(MainWindow)
        self.open_action.setObjectName(u"open_action")
        self.file_action = QAction(MainWindow)
        self.file_action.setObjectName(u"file_action")
        self.file_action.setCheckable(True)
        self.file_action.setChecked(True)
        self.crossline_action = QAction(MainWindow)
        self.crossline_action.setObjectName(u"crossline_action")
        self.crossline_action.setCheckable(True)
        self.crossline_action.setChecked(False)
        self.redo_atn = QAction(MainWindow)
        self.redo_atn.setObjectName(u"redo_atn")
        self.add_action = QAction(MainWindow)
        self.add_action.setObjectName(u"add_action")
        self.export_boxes_action = QAction(MainWindow)
        self.export_boxes_action.setObjectName(u"export_boxes_action")
        self.validate_boxes_action = QAction(MainWindow)
        self.validate_boxes_action.setObjectName(u"validate_boxes_action")
        self.validate_dataset_action = QAction(MainWindow)
        self.validate_dataset_action.setObjectName(u"validate_dataset_action")
        self.add_atn = QAction(MainWindow)
        self.add_atn.setObjectName(u"add_atn")
        self.add_atn.setMenuRole(QAction.MenuRole.NoRole)
        self.imageseting_action = QAction(MainWindow)
        self.imageseting_action.setObjectName(u"imageseting_action")
        self.imageseting_action.setCheckable(True)
        self.imageseting_action.setChecked(True)
        self.segmentsetting_action = QAction(MainWindow)
        self.segmentsetting_action.setObjectName(u"segmentsetting_action")
        self.segmentsetting_action.setCheckable(True)
        self.segmentsetting_action.setChecked(True)
        self.info_action = QAction(MainWindow)
        self.info_action.setObjectName(u"info_action")
        self.info_action.setCheckable(True)
        self.info_action.setChecked(True)
        self.dark_action = QAction(MainWindow)
        self.dark_action.setObjectName(u"dark_action")
        self.dark_action.setCheckable(True)
        self.dark_action.setChecked(True)
        self.light_action = QAction(MainWindow)
        self.light_action.setObjectName(u"light_action")
        self.light_action.setCheckable(True)
        self.filesetting_action = QAction(MainWindow)
        self.filesetting_action.setObjectName(u"filesetting_action")
        self.filesetting_action.setCheckable(True)
        self.filesetting_action.setChecked(True)
        self.data_atn = QAction(MainWindow)
        self.data_atn.setObjectName(u"data_atn")
        self.data_atn.setCheckable(True)
        self.data_atn.setChecked(True)
        self.data_atn.setMenuRole(QAction.MenuRole.NoRole)
        self.about_action = QAction(MainWindow)
        self.about_action.setObjectName(u"about_action")
        self.github_action = QAction(MainWindow)
        self.github_action.setObjectName(u"github_action")
        self.actionhelp = QAction(MainWindow)
        self.actionhelp.setObjectName(u"actionhelp")
        self.direction_action = QAction(MainWindow)
        self.direction_action.setObjectName(u"direction_action")
        self.direction_action.setCheckable(True)
        self.direction_action.setChecked(True)
        self.information_action = QAction(MainWindow)
        self.information_action.setObjectName(u"information_action")
        self.information_action.setCheckable(True)
        self.information_action.setChecked(True)
        self.shortcut_action = QAction(MainWindow)
        self.shortcut_action.setObjectName(u"shortcut_action")
        self.actiongithub = QAction(MainWindow)
        self.actiongithub.setObjectName(u"actiongithub")
        self.actionversion = QAction(MainWindow)
        self.actionversion.setObjectName(u"actionversion")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_5 = QFrame(self.centralwidget)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_5)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.frame_5)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.frame_2 = QFrame(self.splitter)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMinimumSize(QSize(600, 0))
        self.frame_2.setMaximumSize(QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_13 = QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.frame_3 = QFrame(self.frame_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setMinimumSize(QSize(0, 0))
        self.frame_3.setMaximumSize(QSize(16777215, 16777215))
        self.frame_3.setBaseSize(QSize(24, 24))
        self.frame_3.setStyleSheet(u"")
        self.horizontalLayout_2 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.boxPET = QCheckBox(self.frame_3)
        self.boxPET.setObjectName(u"boxPET")
        self.boxPET.setChecked(True)

        self.horizontalLayout_2.addWidget(self.boxPET)

        self.boxCT = QCheckBox(self.frame_3)
        self.boxCT.setObjectName(u"boxCT")
        self.boxCT.setChecked(True)

        self.horizontalLayout_2.addWidget(self.boxCT)

        self.boxSeg = QCheckBox(self.frame_3)
        self.boxSeg.setObjectName(u"boxSeg")
        self.boxSeg.setChecked(True)

        self.horizontalLayout_2.addWidget(self.boxSeg)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.btn_aim = QPushButton(self.frame_3)
        self.btn_aim.setObjectName(u"btn_aim")
        self.btn_aim.setCheckable(True)
        self.btn_aim.setChecked(True)

        self.horizontalLayout_2.addWidget(self.btn_aim)

        self.btn_move = QPushButton(self.frame_3)
        self.btn_move.setObjectName(u"btn_move")
        self.btn_move.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.btn_move)

        self.btn_win = QPushButton(self.frame_3)
        self.btn_win.setObjectName(u"btn_win")
        self.btn_win.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.btn_win)

        self.btn_paint = QPushButton(self.frame_3)
        self.btn_paint.setObjectName(u"btn_paint")
        self.btn_paint.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.btn_paint)

        self.btn_eraser = QPushButton(self.frame_3)
        self.btn_eraser.setObjectName(u"btn_eraser")
        self.btn_eraser.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.btn_eraser)

        self.btn_sam = QPushButton(self.frame_3)
        self.btn_sam.setObjectName(u"btn_sam")
        self.btn_sam.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.btn_sam)

        self.btn_box = QPushButton(self.frame_3)
        self.btn_box.setObjectName(u"btn_box")
        self.btn_box.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.btn_box)


        self.verticalLayout_13.addWidget(self.frame_3)

        self.frame = QFrame(self.frame_2)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.gridLayout = QGridLayout(self.frame)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.frame_H = QFrame(self.frame)
        self.frame_H.setObjectName(u"frame_H")
        self.frame_H.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_H.setFrameShadow(QFrame.Shadow.Raised)

        self.gridLayout.addWidget(self.frame_H, 0, 0, 1, 1)

        self.frame_S = QFrame(self.frame)
        self.frame_S.setObjectName(u"frame_S")
        self.frame_S.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_S.setFrameShadow(QFrame.Shadow.Raised)

        self.gridLayout.addWidget(self.frame_S, 0, 1, 1, 1)

        self.frame_3d = QFrame(self.frame)
        self.frame_3d.setObjectName(u"frame_3d")
        self.frame_3d.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3d.setFrameShadow(QFrame.Shadow.Raised)

        self.gridLayout.addWidget(self.frame_3d, 1, 0, 1, 1)

        self.frame_G = QFrame(self.frame)
        self.frame_G.setObjectName(u"frame_G")
        self.frame_G.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_G.setFrameShadow(QFrame.Shadow.Raised)

        self.gridLayout.addWidget(self.frame_G, 1, 1, 1, 1)


        self.verticalLayout_13.addWidget(self.frame)

        self.splitter.addWidget(self.frame_2)

        self.horizontalLayout.addWidget(self.splitter)


        self.verticalLayout.addWidget(self.frame_5)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1276, 33))
        self.muFile = QMenu(self.menuBar)
        self.muFile.setObjectName(u"muFile")
        self.muView = QMenu(self.menuBar)
        self.muView.setObjectName(u"muView")
        self.menu_3 = QMenu(self.muView)
        self.menu_3.setObjectName(u"menu_3")
        self.menu = QMenu(self.menuBar)
        self.menu.setObjectName(u"menu")
        self.menutheme = QMenu(self.menu)
        self.menutheme.setObjectName(u"menutheme")
        self.menu_2 = QMenu(self.menuBar)
        self.menu_2.setObjectName(u"menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setMinimumSize(QSize(32, 0))
        self.toolBar.setMovable(False)
        MainWindow.addToolBar(Qt.ToolBarArea.LeftToolBarArea, self.toolBar)
        self.toolBar_file = QToolBar(MainWindow)
        self.toolBar_file.setObjectName(u"toolBar_file")
        self.toolBar_file.setMinimumSize(QSize(0, 0))
        self.toolBar_file.setMovable(False)
        self.toolBar_file.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar_file)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setMinimumSize(QSize(230, 39))
        self.dockWidget.setMaximumSize(QSize(500, 524287))
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(Qt.DockWidgetArea.LeftDockWidgetArea|Qt.DockWidgetArea.RightDockWidgetArea)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy1)
        self.verticalLayout_4 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.ImageSetting = QWidget(self.dockWidgetContents)
        self.ImageSetting.setObjectName(u"ImageSetting")

        self.verticalLayout_4.addWidget(self.ImageSetting)

        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget)
        self.dockWidget_4 = QDockWidget(MainWindow)
        self.dockWidget_4.setObjectName(u"dockWidget_4")
        self.dockWidget_4.setMinimumSize(QSize(230, 39))
        self.dockWidget_4.setMaximumSize(QSize(500, 524287))
        self.dockWidget_4.setFloating(False)
        self.dockWidget_4.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidget_4.setAllowedAreas(Qt.DockWidgetArea.LeftDockWidgetArea|Qt.DockWidgetArea.RightDockWidgetArea)
        self.dockWidget_4.setDockLocation(Qt.DockWidgetArea.LeftDockWidgetArea)
        self.dockWidgetContents_4 = QWidget()
        self.dockWidgetContents_4.setObjectName(u"dockWidgetContents_4")
        self.verticalLayout_7 = QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.InfoSetting = QWidget(self.dockWidgetContents_4)
        self.InfoSetting.setObjectName(u"InfoSetting")
        self.InfoSetting.setMinimumSize(QSize(0, 0))
        self.verticalLayout_9 = QVBoxLayout(self.InfoSetting)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_7.addWidget(self.InfoSetting)

        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget_4)
        self.dockWidget_2 = QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName(u"dockWidget_2")
        self.dockWidget_2.setMinimumSize(QSize(230, 39))
        self.dockWidget_2.setMaximumSize(QSize(500, 524287))
        self.dockWidget_2.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidget_2.setAllowedAreas(Qt.DockWidgetArea.LeftDockWidgetArea|Qt.DockWidgetArea.RightDockWidgetArea)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.verticalLayout_8 = QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.FileSetting = QWidget(self.dockWidgetContents_2)
        self.FileSetting.setObjectName(u"FileSetting")

        self.verticalLayout_8.addWidget(self.FileSetting)

        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockWidget_2)
        self.dockWidget_3 = QDockWidget(MainWindow)
        self.dockWidget_3.setObjectName(u"dockWidget_3")
        sizePolicy1.setHeightForWidth(self.dockWidget_3.sizePolicy().hasHeightForWidth())
        self.dockWidget_3.setSizePolicy(sizePolicy1)
        self.dockWidget_3.setMinimumSize(QSize(230, 39))
        self.dockWidget_3.setMaximumSize(QSize(500, 524287))
        self.dockWidget_3.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidget_3.setAllowedAreas(Qt.DockWidgetArea.LeftDockWidgetArea|Qt.DockWidgetArea.RightDockWidgetArea)
        self.dockWidgetContents_5 = QWidget()
        self.dockWidgetContents_5.setObjectName(u"dockWidgetContents_5")
        self.verticalLayout_3 = QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.SegmentSetting = QWidget(self.dockWidgetContents_5)
        self.SegmentSetting.setObjectName(u"SegmentSetting")

        self.verticalLayout_3.addWidget(self.SegmentSetting)

        self.dockWidget_3.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockWidget_3)
        self.dockWidget_4.raise_()

        self.menuBar.addAction(self.muFile.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.muView.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.muFile.addAction(self.open_action)
        self.muFile.addAction(self.add_action)
        self.muFile.addAction(self.export_boxes_action)
        self.muFile.addAction(self.validate_boxes_action)
        self.muFile.addAction(self.validate_dataset_action)
        self.muFile.addAction(self.save_action)
        self.muFile.addAction(self.exit_action)
        self.muView.addAction(self.file_action)
        self.muView.addAction(self.menu_3.menuAction())
        self.menu_3.addAction(self.information_action)
        self.menu_3.addAction(self.direction_action)
        self.menu_3.addAction(self.crossline_action)
        self.menu.addAction(self.filesetting_action)
        self.menu.addAction(self.imageseting_action)
        self.menu.addAction(self.segmentsetting_action)
        self.menu.addAction(self.info_action)
        self.menu.addSeparator()
        self.menu.addAction(self.menutheme.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.shortcut_action)
        self.menutheme.addAction(self.dark_action)
        self.menutheme.addAction(self.light_action)
        self.menu_2.addAction(self.actionversion)
        self.menu_2.addAction(self.actiongithub)
        self.toolBar.addAction(self.data_atn)
        self.toolBar.addAction(self.setting_atn)
        self.toolBar_file.addAction(self.load_atn)
        self.toolBar_file.addAction(self.add_atn)
        self.toolBar_file.addAction(self.save_atn)
        self.toolBar_file.addAction(self.redo_atn)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.setting_atn.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.load_atn.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165", None))
#if QT_CONFIG(shortcut)
        self.load_atn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.save_atn.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
#if QT_CONFIG(shortcut)
        self.save_atn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.exit_action.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.save_action.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u4e3a", None))
        self.open_action.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6\u5939", None))
        self.file_action.setText(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6\u5de5\u5177\u680f", None))
        self.crossline_action.setText(QCoreApplication.translate("MainWindow", u"\u5b9a\u4f4d\u7ebf", None))
        self.redo_atn.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
        self.add_action.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u6807\u6ce8", None))
        self.export_boxes_action.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u6846\u6807\u6ce8", None))
        self.validate_boxes_action.setText(QCoreApplication.translate("MainWindow", u"\u6821\u9a8c\u6846\u6807\u6ce8", None))
        self.validate_dataset_action.setText(QCoreApplication.translate("MainWindow", u"\u6821\u9a8c\u6570\u636e\u96c6", None))
        self.add_atn.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u6807\u6ce8", None))
#if QT_CONFIG(shortcut)
        self.add_atn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.imageseting_action.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u8bbe\u7f6e", None))
        self.segmentsetting_action.setText(QCoreApplication.translate("MainWindow", u"\u6807\u6ce8\u8bbe\u7f6e", None))
        self.info_action.setText(QCoreApplication.translate("MainWindow", u"\u4fe1\u606f\u8bbe\u7f6e", None))
        self.dark_action.setText(QCoreApplication.translate("MainWindow", u"\u6697", None))
#if QT_CONFIG(tooltip)
        self.dark_action.setToolTip(QCoreApplication.translate("MainWindow", u"\u6697", None))
#endif // QT_CONFIG(tooltip)
        self.light_action.setText(QCoreApplication.translate("MainWindow", u"\u4eae", None))
#if QT_CONFIG(tooltip)
        self.light_action.setToolTip(QCoreApplication.translate("MainWindow", u"\u4eae", None))
#endif // QT_CONFIG(tooltip)
        self.filesetting_action.setText(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6\u7ba1\u7406", None))
        self.data_atn.setText(QCoreApplication.translate("MainWindow", u"\u6570\u636e", None))
#if QT_CONFIG(tooltip)
        self.data_atn.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u6570\u636e", None))
#endif // QT_CONFIG(tooltip)
        self.about_action.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.github_action.setText(QCoreApplication.translate("MainWindow", u"github", None))
        self.actionhelp.setText(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.direction_action.setText(QCoreApplication.translate("MainWindow", u"\u65b9\u4f4d", None))
        self.information_action.setText(QCoreApplication.translate("MainWindow", u"\u60a3\u8005\u540d", None))
        self.shortcut_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e", None))
        self.shortcut_action.setIconText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e", None))
        self.actiongithub.setText(QCoreApplication.translate("MainWindow", u"github", None))
        self.actionversion.setText(QCoreApplication.translate("MainWindow", u"\u8f6f\u4ef6\u4fe1\u606f", None))
        self.boxPET.setText(QCoreApplication.translate("MainWindow", u"PET", None))
        self.boxCT.setText(QCoreApplication.translate("MainWindow", u"CT", None))
        self.boxSeg.setText(QCoreApplication.translate("MainWindow", u"Seg", None))
        self.btn_aim.setText(QCoreApplication.translate("MainWindow", u"\u51c6\u5fc3", None))
        self.btn_move.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u52a8", None))
        self.btn_win.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u7a97", None))
        self.btn_paint.setText(QCoreApplication.translate("MainWindow", u"\u6807\u6ce8", None))
        self.btn_eraser.setText(QCoreApplication.translate("MainWindow", u"\u64e6\u9664", None))
        self.btn_sam.setText(QCoreApplication.translate("MainWindow", u"SAM", None))
        self.btn_box.setText(QCoreApplication.translate("MainWindow", u"Box", None))
        self.muFile.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.muView.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u4fe1\u606f", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.menutheme.setTitle(QCoreApplication.translate("MainWindow", u"\u4e3b\u9898", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u4fa7\u680f", None))
        self.toolBar_file.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u4e3b\u5de5\u5177\u680f", None))
        self.dockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u8bbe\u7f6e", None))
        self.dockWidget_4.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u4fe1\u606f\u663e\u793a", None))
        self.dockWidget_2.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6\u7ba1\u7406", None))
        self.dockWidget_3.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u6807\u6ce8\u8bbe\u7f6e", None))
    # retranslateUi

